variables:
  DOCKER_DRIVER: overlay2

stages:
- build

before_script:
    - rm -fr build SOURCES RPMS

.centoscommon: &centoscommon
  stage: build
  tags:
    - moonshot
  script:
    - yum upgrade
    - sed -i "s/\(.\)%{?dist}/\1b$CI_PIPELINE_ID%{?dist}/g" trust_router.spec
    - printf "[moonshot]\nname=moonshot\nbaseurl=https://$NEXUS_USER:$NEXUS_PWD@nexus.ci.ti.ja.net/repository/moonshot/$CI_JOB_NAME\nenabled=1\ngpgcheck=0" > /etc/yum.repos.d/moonshot.repo
    - yum -y install libradsec-devel moonshot-ui-devel moonshot-gss-eap
    - autoreconf -fi
    - ./configure
    - make dist
    - mkdir SOURCES
    - mv trust_router*.tar.gz SOURCES
    - rpmbuild -bb trust_router.spec --define "_topdir `pwd`"
    - for i in RPMS/x86_64/*.rpm; do curl --user "$NEXUS_USER:$NEXUS_PWD" -f --upload-file "$i"  https://nexus.ci.ti.ja.net/repository/moonshot/$CI_JOB_NAME/; done
  artifacts:
    paths:
        - RPMS

.debiancommon: &debiancommon
  stage: build
  tags:
    - moonshot
  script:
    - apt-get -y update && apt-get -y dist-upgrade
    - dch -l ".$CI_JOB_NAME.b$CI_PIPELINE_ID" "Include job ID"
    - "for i in ui mech_eap libradsec; do wget --header \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/moonshot/$i/-/jobs/artifacts/develop/download?job=$CI_JOB_NAME -O deps.zip; unzip deps.zip; done"
    - "dpkg -i build/*.deb || true"
    - apt-get install -fy
    - rm -fr build deps.zip
    - autoreconf -fi
    - ./configure
    - make dist
    - mv trust_router-*.gz ../moonshot-trust-router_3.3.0.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

centos6:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos6:latest
  <<: *centoscommon

centos7:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos7:latest
  <<: *centoscommon

debian8:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian8:latest
  <<: *debiancommon

debian9:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian9:latest
  <<: *debiancommon

ubuntu14:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu14:latest
  <<: *debiancommon

ubuntu16:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu16:latest
  <<: *debiancommon

ubuntu18:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu18:latest
  <<: *debiancommon
