variables:
  DOCKER_DRIVER: overlay2

stages:
- build

.centoscommon: &centoscommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - autoreconf -fi
    - ./configure
    - make dist
    - mkdir SOURCES
    - mv trust_router*.tar.gz SOURCES
    - rpmbuild -ba trust_router.spec --define "_topdir `pwd`"
  artifacts:
    expire_in: 6 months
    paths:
        - RPMS
        - SRPMS

.debiancommon: &debiancommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/DIST/$CI_JOB_NAME/g" debian/changelog
    - debuild -us -uc
    - mkdir build
    - mv ../*.deb ../*.dsc ../*tar* build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*

.alpinecommon: &alpinecommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - adduser -D tmpuser -s /bin/sh
    - adduser tmpuser abuild
    - autoreconf -fi
    - sed -i "s/GZIP_ENV = --best//g" Makefile.in
    - ./configure
    - make dist
    - sudo -u tmpuser abuild checksum
    - sudo -u tmpuser abuild-keygen -an
    - sudo -u tmpuser abuild -r
    - mkdir apks
    - mv /home/tmpuser/packages/*/* apks
  artifacts:
    expire_in: 6 months
    paths:
        - apks/*/*.apk

centos7:
  image: $DOCKER_REGISTRY_URL/centos7:latest
  <<: *centoscommon

centos8:
  image: $DOCKER_REGISTRY_URL/centos8:latest
  <<: *centoscommon

debian9:
  image: $DOCKER_REGISTRY_URL/debian9:latest
  <<: *debiancommon

debian10:
  image: $DOCKER_REGISTRY_URL/debian10:latest
  <<: *debiancommon

raspbian9:
  image: $DOCKER_REGISTRY_URL/raspbian9:latest
  <<: *debiancommon

raspbian10:
  image: $DOCKER_REGISTRY_URL/raspbian10:latest
  <<: *debiancommon

ubuntu16:
  image: $DOCKER_REGISTRY_URL/ubuntu16:latest
  <<: *debiancommon

ubuntu18:
  image: $DOCKER_REGISTRY_URL/ubuntu18:latest
  <<: *debiancommon

ubuntu20:
  image: $DOCKER_REGISTRY_URL/ubuntu20:latest
  <<: *debiancommon

alpine311:
  image: $DOCKER_REGISTRY_URL/alpine311:latest
  <<: *alpinecommon

alpine311_armhf:
  image: $DOCKER_REGISTRY_URL/alpine311_arm:latest
  <<: *alpinecommon

alpine313:
  image: $DOCKER_REGISTRY_URL/alpine313:latest
  <<: *alpinecommon

alpine313_armhf:
  image: $DOCKER_REGISTRY_URL/alpine313_arm:latest
  <<: *alpinecommon
